### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by Redstonerayy** [alexcoder04/rfap-pycli#3]
Building the server on windows, installing the library and connecting to the server works fine.
But uppon entering a command except pwd or help it is not working anymore because of missing
path support.

Error Logs from command line:
```
$ python rfap_pycli.py 
Welcome to rfap-pycli!
server address: localhost
Connecting to localhost...
sent ping
Connected successfully
←[36mrfap> ←[0mhelp   
help is coming soon xD
←[36mrfap> ←[0mpwd
/
←[36mrfap> ←[0mcd aseprite
Traceback (most recent call last):
  File "C:\Users\anton\Programming\rfap\rfap-pycli\rfap_pycli.py", line 142, in <module>
    pwd = command_cd(pwd, args)
  File "C:\Users\anton\Programming\rfap\rfap-pycli\rfap_pycli.py", line 48, in command_cd
    metadata = client.rfap_info(argument)
  File "c:\users\anton\programming\rfap\librfap\librfap\client.py", line 104, in rfap_info
    _, _, metadata, _, _, _ = self.recv_command()
  File "c:\users\anton\programming\rfap\librfap\librfap\client.py", line 52, in recv_command
    data = self.socket.recv(2+4+(16*1024*1024)+4+(16*1024*1024))
ConnectionAbortedError: [WinError 10053] Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
```

**Comment by alexcoder04** [comment]
First question: do you see colored output? In the logs you submitted I can see ANSI sequences like `[36m`, which should actually represent colors (should also work on Windows, because I used the colorama library).

**Comment by alexcoder04** [comment]
You are running the server on Windows as well, aren't you? what do the server logs say?

**Comment by Redstonerayy** [comment]
On Windows 10 with python 3.10 i now get a different error because the rfap-pycli has been updated.
Error from pycli:
[rfap-go-server-11448.log](https://github.com/alexcoder04/rfap-pycli/files/7729939/rfap-go-server-11448.log)

```
$ python rfap-pycli.py 
Welcome to rfap-pycli!
Connecting to localhost:6700...
Traceback (most recent call last):
  File "C:\Users\anton\Programming\rfap\rfap-pycli\rfap-pycli.py", line 285, in <module>
    app = RfapCliApp()
  File "C:\Users\anton\Programming\rfap\rfap-pycli\rfap-pycli.py", line 46, in __init__
    self.cmd_ping()
  File "C:\Users\anton\Programming\rfap\rfap-pycli\rfap-pycli.py", line 213, in cmd_ping
    self.client.rfap_ping()
  File "C:\Users\anton\AppData\Local\Programs\Python\Python310\lib\site-packages\librfap\client.py", line 135, in rfap_ping
    self.recv_data()
  File "C:\Users\anton\AppData\Local\Programs\Python\Python310\lib\site-packages\librfap\client.py", line 84, in recv_data
    if first_metadata["PacketsTotal"] < 1:
KeyError: 'PacketsTotal'
```

**Comment by alexcoder04** [comment]
It looks like you are using an outdated version of [librfap](https://github.com/alexcoder04/librfap). Because of a protocol change, it was updated recently. The server was updated as well, so make sure you are on the latest version there as well.
